name: Update README

on:
  push:
    branches:
      - main # <--- IMPORTANT: Change 'main' to 'master' if your default branch is 'master'
  schedule:
    - cron: "0 */1 * * *" # Runs every hour

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions for the action to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Using the latest stable version

      - name: Generate README
        uses: github/readme-scribe@v1 # <--- THIS IS THE FIX FOR THE DEPRECATION ERROR
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          commit_message: Update generated README
          branch: main # <--- IMPORTANT: Ensure this matches your branch (e.g., 'main' or 'master')
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
